# BVP Stress Detection Pipeline Configuration
# This file contains all configuration parameters for the MLOps pipeline

# Data configuration
data:
  segment_length_sec: 60
  sliding_length_sec: 5
  sampling_rate: 64
  wesad_path: "data/raw/wesad/"
  use_synthetic_data: true  # Set to false to use actual WESAD dataset

# Preprocessing configuration
preprocessing:
  filter_lowcut: 0.7
  filter_highcut: 3.7
  filter_order: 3
  feature_count: 9
  normalization_method: "zscore"  # "zscore" or "minmax"

# Model architecture configuration
model:
  cnn_filters: [8, 16, 8]
  cnn_kernel_sizes: [64, 32, 16]
  cnn_strides: [4, 2, 1]
  dropout_rate: 0.5
  feature_dense_units: 4
  num_classes: 3
  class_names: ["Baseline", "Stress", "Amusement"]

# Training configuration
training:
  batch_size: 500
  epochs: 200
  patience: 70
  validation_split: 0.2
  test_size: 0.2
  random_state: 42
  optimizer: "adam"
  learning_rate: 0.001
  loss: "categorical_crossentropy"
  metrics: ["accuracy", "precision", "recall"]
  early_stopping_monitor: "val_recall"
  early_stopping_mode: "max"
  class_weight_method: "balanced"

# Model optimization configuration
optimization:
  enable_quantization: true
  quantization_type: "int8"  # "int8" or "float16"
  representative_samples: 1000
  optimize_for_size: true
  target_spec_ops: ["TFLITE_BUILTINS_INT8", "TFLITE_BUILTINS"]

# Output paths
paths:
  models_dir: "models"
  results_dir: "results"
  data_dir: "data"
  tflite_dir: "models/tflite"
  esp32_dir: "models/esp32"
  logs_dir: "results/logs"
  metrics_dir: "results/metrics"
  plots_dir: "results/plots"
  saved_models_dir: "models/saved_models"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file_logging: true
  console_logging: true

# ESP32 deployment configuration
esp32:
  hardware:
    ppg_sda_pin: 21
    ppg_scl_pin: 22
    ppg_int_pin: 23
    led_stress_pin: 2
    led_baseline_pin: 4
    led_amusement_pin: 5
    buzzer_pin: 18
  
  model:
    tensor_arena_size: 100000
    segment_length: 3840  # 60 seconds * 64 Hz
    feature_count: 9
    num_classes: 3
  
  timing:
    sample_interval_us: 15625  # 1/64 Hz in microseconds
    inference_interval_us: 60000000  # 60 seconds
  
  communication:
    serial_baud: 115200
    enable_wifi: false
    enable_bluetooth: false

# Feature extraction configuration
features:
  hrv_metrics:
    - "mean_bvp"
    - "std_bvp"
    - "min_bvp"
    - "max_bvp"
    - "heart_rate"
    - "mean_rr"
    - "std_rr"
    - "rmssd"
    - "pnn50"
  
  peak_detection:
    height_threshold: 0.5  # Multiple of standard deviation
    distance_min: 32  # Minimum distance between peaks (0.5 seconds at 64 Hz)
    prominence: 0.1

# Performance targets
performance:
  target_accuracy: 0.90
  target_precision: 0.85
  target_recall: 0.85
  target_f1_score: 0.85
  max_model_size_mb: 1.0
  max_inference_time_ms: 100
  max_memory_usage_kb: 100

# Data augmentation (optional)
augmentation:
  enable: false
  noise_factor: 0.01
  time_shift_range: 0.1
  amplitude_scale_range: [0.9, 1.1]

# Experiment tracking
experiment_tracking:
  enable_mlflow: false
  enable_wandb: false
  experiment_name: "bvp_stress_detection"
  tags:
    - "stress_detection"
    - "bvp"
    - "hcnn"
    - "esp32"
